### ISSUE TITLE
Aiai

### ISSUE THREAD

**Issue by Felps-N** [igoor1/desaula#3]
https://github.com/igoor1/desaula/blob/e7421d0d0268b717e4ad28d359535a4dac2250e7/desaula/atendimento.cs#L12

eu criei o vetor na classe onde eu tenho as funções do menu, pois assim ficaria mais fácil para controlar com o laço de repetição for

https://github.com/igoor1/desaula/blob/e7421d0d0268b717e4ad28d359535a4dac2250e7/desaula/atendimento.cs#L15

os métodos são usados dentro do for, na classe onde há as opções do menu

**Comment by Felps-N** [comment]
você poderia criar o vetor na classe menu

**Comment by igoor1** [comment]
ótima ideia!
